
    alter table context 
        drop constraint FK38B735AF327F008E;

    alter table context 
        drop constraint FK38B735AF5F7A0CC0;

    alter table context_command 
        drop constraint FKDCAF9CBBD5B02B7A;

    alter table context_command_alias 
        drop constraint FKF55DDDCC57BAE308;

    drop table context if exists;

    drop table context_command if exists;

    drop table context_command_alias if exists;

    drop table context_group if exists;

    drop table object if exists;

    create table context (
        context_id bigint generated by default as identity (start with 1),
        is_character_promptable bit,
        entry_command_class_name varchar(255),
        entry_message varchar(255),
        is_listed_in_parent bit,
        max_entries integer,
        max_entries_exceeded_message varchar(255),
        name varchar(255),
        prompt_command_class_name varchar(255),
        child_group_id bigint,
        parent_group_id bigint,
        primary key (context_id)
    );

    create table context_command (
        context_command_id bigint generated by default as identity (start with 1),
        command_class varchar(255) not null,
        context_id bigint not null,
        primary key (context_command_id)
    );

    create table context_command_alias (
        context_command_id bigint not null,
        alias varchar(255)
    );

    create table context_group (
        context_group_id bigint generated by default as identity (start with 1),
        primary key (context_group_id)
    );

    create table object (
        object_id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (object_id)
    );

    alter table context 
        add constraint FK38B735AF327F008E 
        foreign key (child_group_id) 
        references context_group;

    alter table context 
        add constraint FK38B735AF5F7A0CC0 
        foreign key (parent_group_id) 
        references context_group;

    alter table context_command 
        add constraint FKDCAF9CBBD5B02B7A 
        foreign key (context_id) 
        references context;

    alter table context_command_alias 
        add constraint FKF55DDDCC57BAE308 
        foreign key (context_command_id) 
        references context_command;
