
    alter table ACCOUNT_ROLE_COMMAND 
        drop constraint FKB5B205549FA1759B;

    alter table ACCOUNT_ROLE_COMMAND 
        drop constraint FKB5B20554508CA7D2;

    alter table ACCOUNT_ROLE_CONTEXT 
        drop constraint FKB5C35BB8D5B02B7A;

    alter table ACCOUNT_ROLE_CONTEXT 
        drop constraint FKB5C35BB8508CA7D2;

    alter table CHARACTER_ROLE_COMMAND 
        drop constraint FK639449D89FA1759B;

    alter table CHARACTER_ROLE_COMMAND 
        drop constraint FK639449D83684E78E;

    alter table CHARACTER_ROLE_CONTEXT 
        drop constraint FK63A5A03CD5B02B7A;

    alter table CHARACTER_ROLE_CONTEXT 
        drop constraint FK63A5A03C3684E78E;

    alter table account 
        drop constraint FKB9D38A2D508CA7D2;

    alter table character 
        drop constraint FK5D3BBB29BA1A5C8A;

    alter table character 
        drop constraint FK5D3BBB299531FB37;

    alter table context 
        drop constraint FK38B735AF327F008E;

    alter table context 
        drop constraint FK38B735AF5F7A0CC0;

    alter table context_command 
        drop constraint FKDCAF9CBBD5B02B7A;

    alter table context_command_alias 
        drop constraint FKF55DDDCC9FA1759B;

    alter table context_command_parameter 
        drop constraint FK49AADD259FA1759B;

    drop table ACCOUNT_ROLE_COMMAND if exists;

    drop table ACCOUNT_ROLE_CONTEXT if exists;

    drop table CHARACTER_ROLE_COMMAND if exists;

    drop table CHARACTER_ROLE_CONTEXT if exists;

    drop table account if exists;

    drop table account_role if exists;

    drop table character if exists;

    drop table character_role if exists;

    drop table context if exists;

    drop table context_command if exists;

    drop table context_command_alias if exists;

    drop table context_command_parameter if exists;

    drop table context_group if exists;

    drop table message if exists;

    drop table object if exists;

    create table ACCOUNT_ROLE_COMMAND (
        ACCOUNT_ROLE_ID bigint not null,
        CONTEXT_COMMAND_ID bigint not null,
        primary key (ACCOUNT_ROLE_ID, CONTEXT_COMMAND_ID)
    );

    create table ACCOUNT_ROLE_CONTEXT (
        ACCOUNT_ROLE_ID bigint not null,
        CONTEXT_ID bigint not null,
        primary key (ACCOUNT_ROLE_ID, CONTEXT_ID)
    );

    create table CHARACTER_ROLE_COMMAND (
        ACCOUNT_ROLE_ID bigint not null,
        CONTEXT_COMMAND_ID bigint not null,
        primary key (ACCOUNT_ROLE_ID, CONTEXT_COMMAND_ID)
    );

    create table CHARACTER_ROLE_CONTEXT (
        ACCOUNT_ROLE_ID bigint not null,
        CONTEXT_ID bigint not null,
        primary key (ACCOUNT_ROLE_ID, CONTEXT_ID)
    );

    create table account (
        id bigint generated by default as identity (start with 1),
        login varchar(255),
        password varchar(255),
        account_role_id bigint not null,
        primary key (id)
    );

    create table account_role (
        id bigint generated by default as identity (start with 1),
        name varchar(255) not null,
        primary key (id)
    );

    create table character (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        account_id bigint not null,
        character_role_id bigint not null,
        primary key (id)
    );

    create table character_role (
        id bigint generated by default as identity (start with 1),
        name varchar(255) not null,
        primary key (id)
    );

    create table context (
        id bigint generated by default as identity (start with 1),
        entry_message varchar(255),
        max_entries integer,
        max_entries_exceeded_message varchar(255),
        name varchar(255),
        prompt varchar(255),
        is_secure bit,
        child_group_id bigint,
        parent_group_id bigint,
        primary key (id)
    );

    create table context_command (
        id bigint generated by default as identity (start with 1),
        command_class varchar(255) not null,
        flag varchar(255),
        description varchar(255),
        name varchar(255),
        sequence integer,
        context_id bigint not null,
        primary key (id)
    );

    create table context_command_alias (
        context_command_alias_id integer generated by default as identity (start with 1),
        is_accelerator bit not null,
        alias varchar(255) not null,
        is_bullet bit not null,
        context_command_id bigint not null,
        primary key (context_command_alias_id)
    );

    create table context_command_parameter (
        id integer generated by default as identity (start with 1),
        sequence integer not null,
        param_value varchar(255) not null,
        context_command_id bigint not null,
        primary key (id)
    );

    create table context_group (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    );

    create table message (
        id bigint generated by default as identity (start with 1),
        message varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table object (
        object_id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (object_id)
    );

    alter table ACCOUNT_ROLE_COMMAND 
        add constraint FKB5B205549FA1759B 
        foreign key (CONTEXT_COMMAND_ID) 
        references context_command;

    alter table ACCOUNT_ROLE_COMMAND 
        add constraint FKB5B20554508CA7D2 
        foreign key (ACCOUNT_ROLE_ID) 
        references account_role;

    alter table ACCOUNT_ROLE_CONTEXT 
        add constraint FKB5C35BB8D5B02B7A 
        foreign key (CONTEXT_ID) 
        references context;

    alter table ACCOUNT_ROLE_CONTEXT 
        add constraint FKB5C35BB8508CA7D2 
        foreign key (ACCOUNT_ROLE_ID) 
        references account_role;

    alter table CHARACTER_ROLE_COMMAND 
        add constraint FK639449D89FA1759B 
        foreign key (CONTEXT_COMMAND_ID) 
        references context_command;

    alter table CHARACTER_ROLE_COMMAND 
        add constraint FK639449D83684E78E 
        foreign key (ACCOUNT_ROLE_ID) 
        references character_role;

    alter table CHARACTER_ROLE_CONTEXT 
        add constraint FK63A5A03CD5B02B7A 
        foreign key (CONTEXT_ID) 
        references context;

    alter table CHARACTER_ROLE_CONTEXT 
        add constraint FK63A5A03C3684E78E 
        foreign key (ACCOUNT_ROLE_ID) 
        references character_role;

    alter table account 
        add constraint FKB9D38A2D508CA7D2 
        foreign key (account_role_id) 
        references account_role;

    alter table character 
        add constraint FK5D3BBB29BA1A5C8A 
        foreign key (character_role_id) 
        references character_role;

    alter table character 
        add constraint FK5D3BBB299531FB37 
        foreign key (account_id) 
        references account;

    alter table context 
        add constraint FK38B735AF327F008E 
        foreign key (child_group_id) 
        references context_group;

    alter table context 
        add constraint FK38B735AF5F7A0CC0 
        foreign key (parent_group_id) 
        references context_group;

    alter table context_command 
        add constraint FKDCAF9CBBD5B02B7A 
        foreign key (context_id) 
        references context;

    alter table context_command_alias 
        add constraint FKF55DDDCC9FA1759B 
        foreign key (context_command_id) 
        references context_command;

    alter table context_command_parameter 
        add constraint FK49AADD259FA1759B 
        foreign key (context_command_id) 
        references context_command;
