
    alter table context 
        drop constraint FK38B735AF4996B24F;

    alter table context_command 
        drop constraint FKDCAF9CBB4996B24F;

    drop table context if exists;

    drop table context_command if exists;

    drop table object if exists;

    create table context (
        context_id bigint not null,
        name varchar(255),
        primary key (context_id)
    );

    create table context_command (
        context_command_id bigint not null,
        command varchar(255) not null,
        context_id bigint not null,
        primary key (context_command_id)
    );

    create table object (
        object_id bigint generated by default as identity (start with 1),
        primary key (object_id)
    );

    alter table context 
        add constraint FK38B735AF4996B24F 
        foreign key (context_id) 
        references context;

    alter table context_command 
        add constraint FKDCAF9CBB4996B24F 
        foreign key (context_id) 
        references context;
